Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 160
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/ClassLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 32
Style/Documentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'app/models/ckeditor/*'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
