Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/ClassLength:
  Max: 30
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 32
Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
