secret_key_base: somesecret

development:
  db_user: createrailsapp
  db_password: createrailsapp
  db_name: createrailsapp_development

test:
  db_user: createrailsapp
  db_password: createrailsapp
  db_name: createrailsapp_test

staging:
  db_user: createrailsapp
  db_password: createrailsapp
  db_name: createrailsapp_staging

production:
  db_user: createrailsapp
  db_password: createrailsapp
  db_name: createrailsapp_production
